### PR TITLE
Do not fail if a namespace cannot be loaded.

### PR DESCRIPTION
**Pull request by jimhester**
This fixes devtools failures when using sessioninfo

https://travis-ci.org/hadley/devtools/jobs/260288634#L823-L827

### CODE REVIEW

**Comment by gaborcsardi** [comment]
Thanks! Wouldn't it be better no to try to load it at all?

The point of using getNamespaceVersion was to detect the rare case when the loaded version is different from the on-disk version. If the package is not loaded, we can just keep the loaded version empty.

Anyway, I can merge this now, and change it later.

**Comment by jimhester** [comment]
Ok updated to only get namespace versions for loaded namespaces.

**Comment by gaborcsardi** [comment]
Are the NAs printed? How does the printed output look?

**Comment by gaborcsardi** [comment]
I'll update the mocked test, don't worry about that.

**Comment by jimhester** [comment]
Hmm `NA` actually causes errors from `base::package_version()` because it is not a valid package version, as done `""`. `"0.0.0"` works, but the output is kind of gross.

```
─ Packages ───────────────────────────────────────────────
 package           * version    date       source

 acepack             0.0.0 (!)  2016-10-29 CRAN (R 3.4.0)

 AnnotationDbi       0.0.0 (!)  2017-04-25 Bioconductor

 ape                 0.0.0 (!)  2017-02-14 CRAN (R 3.4.0)

 archive             0.0.0 (!)  2017-07-28 Github (jimhester/archive@a203312)

 assertive.base      0.0.0 (!)  2016-12-30 CRAN (R 3.4.0)

 assertthat          0.2.0      2017-04-11 CRAN (R 3.4.0)
```

**Comment by gaborcsardi** [comment]
Yeah, I am afraid we need to change the print method.

**Comment by gaborcsardi** [comment]
Somewhere around here: https://github.com/r-lib/sessioninfo/blob/8de11634774a92b15decacbeab2f7a827fd0fb2c/R/package-info.R#L132

If it is not loaded, just use the on-disk version.

**Comment by jimhester** [comment]
Ok turns out if you use `package_version(NA, strict = FALSE)` we get an `NA` package version, which we can then handle in the print method, which looks nicer and should still catch the case where a loaded version is different than the installed version as before (https://github.com/r-lib/sessioninfo/pull/4/commits/3806e7c7420545f2abf14504360afd99c24442e7).

**Comment by gaborcsardi** [comment]
Great! Thanks!

**Pull request merged**
